version: "3"

services:
  app:
    userns_mode: keep-id
    image: mcr.microsoft.com/devcontainers/typescript-node:0-20
    command: sleep infinity
    volumes:
      - ./:/home/node/workspace:z
      - .vscode-server/:/home/node/.vscode-server:z
