@baseURL=http://127.0.0.1:5001/dental-dashboard/us-central1/v1-patients

POST {{baseURL}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.idToken}}

{
  "fullName": "Meshach Matheus"
}

###

# @name login
POST http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=[API_KEY]
Accept: application/json
Content-Type: application/json

{
  "email": "anas@anasdidi.dev",
  "password": "p@ssw0rd",
  "returnSecureToken": true
}
